[package]
name = "ssa"
description = "Solidty Static Analysis"
version = "0.1.2"
authors = ["Duy Tai Nguyen duytai.cse@gmail.com"]
edition = "2018"
repository = "https://github.com/duytai/ssa"
license = "GPL-3.0"

[dependencies]
json = "0.11.13"
reqwest = "0.9.18"
regex = "1"
